// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shiqinfeng1/goframe-ddd/internal/infrastructure/repositories/ent/predicate"
	"github.com/shiqinfeng1/goframe-ddd/internal/infrastructure/repositories/ent/sendchunk"
	"github.com/shiqinfeng1/goframe-ddd/internal/infrastructure/repositories/ent/sendfile"
)

// SendFileQuery is the builder for querying SendFile entities.
type SendFileQuery struct {
	config
	ctx            *QueryContext
	order          []sendfile.OrderOption
	inters         []Interceptor
	predicates     []predicate.SendFile
	withSendChunks *SendChunkQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SendFileQuery builder.
func (sfq *SendFileQuery) Where(ps ...predicate.SendFile) *SendFileQuery {
	sfq.predicates = append(sfq.predicates, ps...)
	return sfq
}

// Limit the number of records to be returned by this query.
func (sfq *SendFileQuery) Limit(limit int) *SendFileQuery {
	sfq.ctx.Limit = &limit
	return sfq
}

// Offset to start from.
func (sfq *SendFileQuery) Offset(offset int) *SendFileQuery {
	sfq.ctx.Offset = &offset
	return sfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sfq *SendFileQuery) Unique(unique bool) *SendFileQuery {
	sfq.ctx.Unique = &unique
	return sfq
}

// Order specifies how the records should be ordered.
func (sfq *SendFileQuery) Order(o ...sendfile.OrderOption) *SendFileQuery {
	sfq.order = append(sfq.order, o...)
	return sfq
}

// QuerySendChunks chains the current query on the "send_chunks" edge.
func (sfq *SendFileQuery) QuerySendChunks() *SendChunkQuery {
	query := (&SendChunkClient{config: sfq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sfq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sendfile.Table, sendfile.FieldID, selector),
			sqlgraph.To(sendchunk.Table, sendchunk.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, sendfile.SendChunksTable, sendfile.SendChunksColumn),
		)
		fromU = sqlgraph.SetNeighbors(sfq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SendFile entity from the query.
// Returns a *NotFoundError when no SendFile was found.
func (sfq *SendFileQuery) First(ctx context.Context) (*SendFile, error) {
	nodes, err := sfq.Limit(1).All(setContextOp(ctx, sfq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sendfile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sfq *SendFileQuery) FirstX(ctx context.Context) *SendFile {
	node, err := sfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SendFile ID from the query.
// Returns a *NotFoundError when no SendFile ID was found.
func (sfq *SendFileQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sfq.Limit(1).IDs(setContextOp(ctx, sfq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sendfile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sfq *SendFileQuery) FirstIDX(ctx context.Context) int {
	id, err := sfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SendFile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SendFile entity is found.
// Returns a *NotFoundError when no SendFile entities are found.
func (sfq *SendFileQuery) Only(ctx context.Context) (*SendFile, error) {
	nodes, err := sfq.Limit(2).All(setContextOp(ctx, sfq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sendfile.Label}
	default:
		return nil, &NotSingularError{sendfile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sfq *SendFileQuery) OnlyX(ctx context.Context) *SendFile {
	node, err := sfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SendFile ID in the query.
// Returns a *NotSingularError when more than one SendFile ID is found.
// Returns a *NotFoundError when no entities are found.
func (sfq *SendFileQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sfq.Limit(2).IDs(setContextOp(ctx, sfq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sendfile.Label}
	default:
		err = &NotSingularError{sendfile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sfq *SendFileQuery) OnlyIDX(ctx context.Context) int {
	id, err := sfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SendFiles.
func (sfq *SendFileQuery) All(ctx context.Context) ([]*SendFile, error) {
	ctx = setContextOp(ctx, sfq.ctx, ent.OpQueryAll)
	if err := sfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SendFile, *SendFileQuery]()
	return withInterceptors[[]*SendFile](ctx, sfq, qr, sfq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sfq *SendFileQuery) AllX(ctx context.Context) []*SendFile {
	nodes, err := sfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SendFile IDs.
func (sfq *SendFileQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sfq.ctx.Unique == nil && sfq.path != nil {
		sfq.Unique(true)
	}
	ctx = setContextOp(ctx, sfq.ctx, ent.OpQueryIDs)
	if err = sfq.Select(sendfile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sfq *SendFileQuery) IDsX(ctx context.Context) []int {
	ids, err := sfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sfq *SendFileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sfq.ctx, ent.OpQueryCount)
	if err := sfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sfq, querierCount[*SendFileQuery](), sfq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sfq *SendFileQuery) CountX(ctx context.Context) int {
	count, err := sfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sfq *SendFileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sfq.ctx, ent.OpQueryExist)
	switch _, err := sfq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sfq *SendFileQuery) ExistX(ctx context.Context) bool {
	exist, err := sfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SendFileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sfq *SendFileQuery) Clone() *SendFileQuery {
	if sfq == nil {
		return nil
	}
	return &SendFileQuery{
		config:         sfq.config,
		ctx:            sfq.ctx.Clone(),
		order:          append([]sendfile.OrderOption{}, sfq.order...),
		inters:         append([]Interceptor{}, sfq.inters...),
		predicates:     append([]predicate.SendFile{}, sfq.predicates...),
		withSendChunks: sfq.withSendChunks.Clone(),
		// clone intermediate query.
		sql:  sfq.sql.Clone(),
		path: sfq.path,
	}
}

// WithSendChunks tells the query-builder to eager-load the nodes that are connected to
// the "send_chunks" edge. The optional arguments are used to configure the query builder of the edge.
func (sfq *SendFileQuery) WithSendChunks(opts ...func(*SendChunkQuery)) *SendFileQuery {
	query := (&SendChunkClient{config: sfq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sfq.withSendChunks = query
	return sfq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TaskID string `json:"task_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SendFile.Query().
//		GroupBy(sendfile.FieldTaskID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sfq *SendFileQuery) GroupBy(field string, fields ...string) *SendFileGroupBy {
	sfq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SendFileGroupBy{build: sfq}
	grbuild.flds = &sfq.ctx.Fields
	grbuild.label = sendfile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TaskID string `json:"task_id,omitempty"`
//	}
//
//	client.SendFile.Query().
//		Select(sendfile.FieldTaskID).
//		Scan(ctx, &v)
func (sfq *SendFileQuery) Select(fields ...string) *SendFileSelect {
	sfq.ctx.Fields = append(sfq.ctx.Fields, fields...)
	sbuild := &SendFileSelect{SendFileQuery: sfq}
	sbuild.label = sendfile.Label
	sbuild.flds, sbuild.scan = &sfq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SendFileSelect configured with the given aggregations.
func (sfq *SendFileQuery) Aggregate(fns ...AggregateFunc) *SendFileSelect {
	return sfq.Select().Aggregate(fns...)
}

func (sfq *SendFileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sfq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sfq); err != nil {
				return err
			}
		}
	}
	for _, f := range sfq.ctx.Fields {
		if !sendfile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sfq.path != nil {
		prev, err := sfq.path(ctx)
		if err != nil {
			return err
		}
		sfq.sql = prev
	}
	return nil
}

func (sfq *SendFileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SendFile, error) {
	var (
		nodes       = []*SendFile{}
		_spec       = sfq.querySpec()
		loadedTypes = [1]bool{
			sfq.withSendChunks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SendFile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SendFile{config: sfq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sfq.withSendChunks; query != nil {
		if err := sfq.loadSendChunks(ctx, query, nodes,
			func(n *SendFile) { n.Edges.SendChunks = []*SendChunk{} },
			func(n *SendFile, e *SendChunk) { n.Edges.SendChunks = append(n.Edges.SendChunks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sfq *SendFileQuery) loadSendChunks(ctx context.Context, query *SendChunkQuery, nodes []*SendFile, init func(*SendFile), assign func(*SendFile, *SendChunk)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*SendFile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(sendchunk.FieldSendfileID)
	}
	query.Where(predicate.SendChunk(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(sendfile.SendChunksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SendfileID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "sendfile_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (sfq *SendFileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sfq.querySpec()
	_spec.Node.Columns = sfq.ctx.Fields
	if len(sfq.ctx.Fields) > 0 {
		_spec.Unique = sfq.ctx.Unique != nil && *sfq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sfq.driver, _spec)
}

func (sfq *SendFileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sendfile.Table, sendfile.Columns, sqlgraph.NewFieldSpec(sendfile.FieldID, field.TypeInt))
	_spec.From = sfq.sql
	if unique := sfq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sfq.path != nil {
		_spec.Unique = true
	}
	if fields := sfq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sendfile.FieldID)
		for i := range fields {
			if fields[i] != sendfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sfq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sfq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sfq *SendFileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sfq.driver.Dialect())
	t1 := builder.Table(sendfile.Table)
	columns := sfq.ctx.Fields
	if len(columns) == 0 {
		columns = sendfile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sfq.sql != nil {
		selector = sfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sfq.ctx.Unique != nil && *sfq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sfq.predicates {
		p(selector)
	}
	for _, p := range sfq.order {
		p(selector)
	}
	if offset := sfq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sfq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SendFileGroupBy is the group-by builder for SendFile entities.
type SendFileGroupBy struct {
	selector
	build *SendFileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sfgb *SendFileGroupBy) Aggregate(fns ...AggregateFunc) *SendFileGroupBy {
	sfgb.fns = append(sfgb.fns, fns...)
	return sfgb
}

// Scan applies the selector query and scans the result into the given value.
func (sfgb *SendFileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sfgb.build.ctx, ent.OpQueryGroupBy)
	if err := sfgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SendFileQuery, *SendFileGroupBy](ctx, sfgb.build, sfgb, sfgb.build.inters, v)
}

func (sfgb *SendFileGroupBy) sqlScan(ctx context.Context, root *SendFileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sfgb.fns))
	for _, fn := range sfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sfgb.flds)+len(sfgb.fns))
		for _, f := range *sfgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sfgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sfgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SendFileSelect is the builder for selecting fields of SendFile entities.
type SendFileSelect struct {
	*SendFileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sfs *SendFileSelect) Aggregate(fns ...AggregateFunc) *SendFileSelect {
	sfs.fns = append(sfs.fns, fns...)
	return sfs
}

// Scan applies the selector query and scans the result into the given value.
func (sfs *SendFileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sfs.ctx, ent.OpQuerySelect)
	if err := sfs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SendFileQuery, *SendFileSelect](ctx, sfs.SendFileQuery, sfs, sfs.inters, v)
}

func (sfs *SendFileSelect) sqlScan(ctx context.Context, root *SendFileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sfs.fns))
	for _, fn := range sfs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sfs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
