services:
  mgrid-server:
    image: "debian12-for-mgrid:${IMAGE_VERSION:-latest}"
    container_name: mgrid-server
    restart: unless-stopped
    entrypoint: ["/app/mgrid","--config","/app/config/config.yaml"]
    volumes: 
      # 运行数据挂载到宿主机独立存储空间中，防止占满系统存储空间
      - ./running/log-mgrid:/app/log
      - ./running/data-mgrid:/app/data
      # 映射程序和配置
      - ./artifacts/config:/app/config
      - ./artifacts/bin/${os:-linux}/${arch:-arm64}/mgrid:/app/mgrid
      - ./artifacts/bin/${os:-linux}/${arch:-arm64}/nats:/app/nats
      # 映射docker.sock及compose相关文件 (可选，在容器内通过sdk操作容器时使用)
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    ports:
      - "31080-31082:31080-31082" # http业务服务端口 grpc服务端口 文件传输服务端口 宿主机监听dockercompose服务
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 容器内访问宿主机服务
    # 设置优雅退出超时时间为 30 秒
    stop_grace_period: 30s
    # 可选：设置停止信号
    stop_signal: SIGTERM
    # 可选：设置健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:31080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      restart_policy:
        condition: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - ENV_VARIABLE=value
    # security_opt:
    #   - no-new-privileges:true  # 防止容器内进程提权
    # cap_drop:
    #   - ALL  #容器内的进程默认不具备任何额外的系统权限
    cap_add:
      - NET_BIND_SERVICE   #容器内的非 root 进程可以绑定到低于 1024 的端口
    ulimits:
      nproc: 65535   #用户或进程可以创建的最大进程数量
      nofile:
        soft: 100000   #进程默认可以打开的最大文件描述符数量
        hard: 200000   #进程可以通过系统调用临时提高软限制，但不能超过硬限制
    networks:
      - mgrid-network  # 显式指定网络
  
  nats-server:
    image: nats-for-mgrid:latest
    container_name: nats-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes: 
      # 运行数据挂载到宿主机独立存储空间中，防止占满系统存储空间
      - ./running/log-nats:/var/log/nats
      - ./running/data-nats:/data
      - ./artifacts/nats-server.conf:/etc/nats/nats-server.conf
    # command: ["-c", "/etc/nats/nats-server.conf"]  # 指定配置文件路径
    ports:
      - "4222:4222"  # nats服务端口
      - "8222:8222"  # nats运维监控端口
      - "6222:6222"  
    networks:
      - mgrid-network  # 显式指定网络
  
  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - mgrid-network  # 显式指定网络
networks:
  mgrid-network:
    external: true
    name: mgrid_network