services:
  mgrid-runtime:
    image: runtime-infrastructure:latest
    container_name: mgrid-runtime
    restart: unless-stopped
    volumes:
      - ./artifacts:/app
      - ./artifacts/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./artifacts/nats-server.conf:/etc/nats/nats-server.conf
      - ./running/var-log-supervisor:/var/log/supervisor
      - ./running/var-log-nats:/var/log/nats
      - ./running/redis-data:/var/lib/redis        #TODO 挂载到独立存储空间中，防止占满系统存储空间
      - ./running/nats-data:/var/lib/nats        #TODO 挂载到独立存储空间中，防止占满系统存储空间
    working_dir: /app
    networks:
      - mgrid_network
    ports:
      - "4222:4222" 
      - "31080:31080" 
      - "31081:31081" 
      - "31082:31082" 
    stop_grace_period: 10s
    deploy:
      restart_policy:
        condition: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:31080/health"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    environment:
      - ENV_VARIABLE=value
    # security_opt:
    #   - no-new-privileges:true  # 防止容器内进程提权
    # cap_drop:
    #   - ALL  #容器内的进程默认不具备任何额外的系统权限
    cap_add:
      - NET_BIND_SERVICE   #容器内的非 root 进程可以绑定到低于 1024 的端口
    ulimits:
      nproc: 65535   #用户或进程可以创建的最大进程数量
      nofile:
        soft: 100000   #进程默认可以打开的最大文件描述符数量
        hard: 200000   #进程可以通过系统调用临时提高软限制，但不能超过硬限制

# 定义自定义网络
networks:
  mgrid_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16