services:
  mgrid-runtime:
    image: "runtime-infrastructure:latest"
    container_name: mgrid-runtime
    restart: unless-stopped
    volumes: 
      # 运行数据挂载到宿主机独立存储空间中，防止占满系统存储空间
      - ./running/log-mgrid:/app/log
      - ./running/log-supervisor:/var/log/supervisor
      - ./running/log-nats:/var/log/nats
      - ./running/data-mgrid:/app/data
      - ./running/data-nats:/var/lib/nats     
      # 映射程序和配置
      - ./artifacts/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./artifacts/nats-server.conf:/etc/nats/nats-server.conf
      - ./artifacts/config:/app/config
      - ./artifacts/mgrid:/app/mgrid
      # 映射docker.sock及compose相关文件
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/app/.env
      - ./docker-compose.yml:/app/docker-compose.yml
    working_dir: /app
    networks:
      - mgrid_network
    ports:
      - "4222:4222"  # nats服务端口
      - "8222:8222"  # nats运维监控端口
      - "31080:31080" # http业务服务端口
      - "31081:31081" # grpc服务端口
      - "31082:31082" # 文件传输服务端口
    stop_grace_period: 10s
    deploy:
      restart_policy:
        condition: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:31080/health"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    environment:
      - ENV_VARIABLE=value
    # security_opt:
    #   - no-new-privileges:true  # 防止容器内进程提权
    # cap_drop:
    #   - ALL  #容器内的进程默认不具备任何额外的系统权限
    cap_add:
      - NET_BIND_SERVICE   #容器内的非 root 进程可以绑定到低于 1024 的端口
    ulimits:
      nproc: 65535   #用户或进程可以创建的最大进程数量
      nofile:
        soft: 100000   #进程默认可以打开的最大文件描述符数量
        hard: 200000   #进程可以通过系统调用临时提高软限制，但不能超过硬限制
  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - mgrid_network
# 定义自定义网络
networks:
  mgrid_network:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.28.0.0/16