// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shiqinfeng1/goframe-ddd/internal/demo/infrastructure/repositories/ent/predicate"
	"github.com/shiqinfeng1/goframe-ddd/internal/demo/infrastructure/repositories/ent/recvchunk"
	"github.com/shiqinfeng1/goframe-ddd/internal/demo/infrastructure/repositories/ent/recvfile"
)

// RecvChunkQuery is the builder for querying RecvChunk entities.
type RecvChunkQuery struct {
	config
	ctx          *QueryContext
	order        []recvchunk.OrderOption
	inters       []Interceptor
	predicates   []predicate.RecvChunk
	withRecvFile *RecvFileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RecvChunkQuery builder.
func (rcq *RecvChunkQuery) Where(ps ...predicate.RecvChunk) *RecvChunkQuery {
	rcq.predicates = append(rcq.predicates, ps...)
	return rcq
}

// Limit the number of records to be returned by this query.
func (rcq *RecvChunkQuery) Limit(limit int) *RecvChunkQuery {
	rcq.ctx.Limit = &limit
	return rcq
}

// Offset to start from.
func (rcq *RecvChunkQuery) Offset(offset int) *RecvChunkQuery {
	rcq.ctx.Offset = &offset
	return rcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rcq *RecvChunkQuery) Unique(unique bool) *RecvChunkQuery {
	rcq.ctx.Unique = &unique
	return rcq
}

// Order specifies how the records should be ordered.
func (rcq *RecvChunkQuery) Order(o ...recvchunk.OrderOption) *RecvChunkQuery {
	rcq.order = append(rcq.order, o...)
	return rcq
}

// QueryRecvFile chains the current query on the "recv_file" edge.
func (rcq *RecvChunkQuery) QueryRecvFile() *RecvFileQuery {
	query := (&RecvFileClient{config: rcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recvchunk.Table, recvchunk.FieldID, selector),
			sqlgraph.To(recvfile.Table, recvfile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recvchunk.RecvFileTable, recvchunk.RecvFileColumn),
		)
		fromU = sqlgraph.SetNeighbors(rcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RecvChunk entity from the query.
// Returns a *NotFoundError when no RecvChunk was found.
func (rcq *RecvChunkQuery) First(ctx context.Context) (*RecvChunk, error) {
	nodes, err := rcq.Limit(1).All(setContextOp(ctx, rcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{recvchunk.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rcq *RecvChunkQuery) FirstX(ctx context.Context) *RecvChunk {
	node, err := rcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RecvChunk ID from the query.
// Returns a *NotFoundError when no RecvChunk ID was found.
func (rcq *RecvChunkQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rcq.Limit(1).IDs(setContextOp(ctx, rcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{recvchunk.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rcq *RecvChunkQuery) FirstIDX(ctx context.Context) int {
	id, err := rcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RecvChunk entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RecvChunk entity is found.
// Returns a *NotFoundError when no RecvChunk entities are found.
func (rcq *RecvChunkQuery) Only(ctx context.Context) (*RecvChunk, error) {
	nodes, err := rcq.Limit(2).All(setContextOp(ctx, rcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{recvchunk.Label}
	default:
		return nil, &NotSingularError{recvchunk.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rcq *RecvChunkQuery) OnlyX(ctx context.Context) *RecvChunk {
	node, err := rcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RecvChunk ID in the query.
// Returns a *NotSingularError when more than one RecvChunk ID is found.
// Returns a *NotFoundError when no entities are found.
func (rcq *RecvChunkQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rcq.Limit(2).IDs(setContextOp(ctx, rcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{recvchunk.Label}
	default:
		err = &NotSingularError{recvchunk.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rcq *RecvChunkQuery) OnlyIDX(ctx context.Context) int {
	id, err := rcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RecvChunks.
func (rcq *RecvChunkQuery) All(ctx context.Context) ([]*RecvChunk, error) {
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryAll)
	if err := rcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RecvChunk, *RecvChunkQuery]()
	return withInterceptors[[]*RecvChunk](ctx, rcq, qr, rcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rcq *RecvChunkQuery) AllX(ctx context.Context) []*RecvChunk {
	nodes, err := rcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RecvChunk IDs.
func (rcq *RecvChunkQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rcq.ctx.Unique == nil && rcq.path != nil {
		rcq.Unique(true)
	}
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryIDs)
	if err = rcq.Select(recvchunk.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rcq *RecvChunkQuery) IDsX(ctx context.Context) []int {
	ids, err := rcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rcq *RecvChunkQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryCount)
	if err := rcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rcq, querierCount[*RecvChunkQuery](), rcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rcq *RecvChunkQuery) CountX(ctx context.Context) int {
	count, err := rcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rcq *RecvChunkQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryExist)
	switch _, err := rcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rcq *RecvChunkQuery) ExistX(ctx context.Context) bool {
	exist, err := rcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RecvChunkQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rcq *RecvChunkQuery) Clone() *RecvChunkQuery {
	if rcq == nil {
		return nil
	}
	return &RecvChunkQuery{
		config:       rcq.config,
		ctx:          rcq.ctx.Clone(),
		order:        append([]recvchunk.OrderOption{}, rcq.order...),
		inters:       append([]Interceptor{}, rcq.inters...),
		predicates:   append([]predicate.RecvChunk{}, rcq.predicates...),
		withRecvFile: rcq.withRecvFile.Clone(),
		// clone intermediate query.
		sql:  rcq.sql.Clone(),
		path: rcq.path,
	}
}

// WithRecvFile tells the query-builder to eager-load the nodes that are connected to
// the "recv_file" edge. The optional arguments are used to configure the query builder of the edge.
func (rcq *RecvChunkQuery) WithRecvFile(opts ...func(*RecvFileQuery)) *RecvChunkQuery {
	query := (&RecvFileClient{config: rcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rcq.withRecvFile = query
	return rcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RecvfileID int `json:"recvfile_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RecvChunk.Query().
//		GroupBy(recvchunk.FieldRecvfileID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rcq *RecvChunkQuery) GroupBy(field string, fields ...string) *RecvChunkGroupBy {
	rcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RecvChunkGroupBy{build: rcq}
	grbuild.flds = &rcq.ctx.Fields
	grbuild.label = recvchunk.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RecvfileID int `json:"recvfile_id,omitempty"`
//	}
//
//	client.RecvChunk.Query().
//		Select(recvchunk.FieldRecvfileID).
//		Scan(ctx, &v)
func (rcq *RecvChunkQuery) Select(fields ...string) *RecvChunkSelect {
	rcq.ctx.Fields = append(rcq.ctx.Fields, fields...)
	sbuild := &RecvChunkSelect{RecvChunkQuery: rcq}
	sbuild.label = recvchunk.Label
	sbuild.flds, sbuild.scan = &rcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RecvChunkSelect configured with the given aggregations.
func (rcq *RecvChunkQuery) Aggregate(fns ...AggregateFunc) *RecvChunkSelect {
	return rcq.Select().Aggregate(fns...)
}

func (rcq *RecvChunkQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rcq); err != nil {
				return err
			}
		}
	}
	for _, f := range rcq.ctx.Fields {
		if !recvchunk.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rcq.path != nil {
		prev, err := rcq.path(ctx)
		if err != nil {
			return err
		}
		rcq.sql = prev
	}
	return nil
}

func (rcq *RecvChunkQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RecvChunk, error) {
	var (
		nodes       = []*RecvChunk{}
		_spec       = rcq.querySpec()
		loadedTypes = [1]bool{
			rcq.withRecvFile != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RecvChunk).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RecvChunk{config: rcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rcq.withRecvFile; query != nil {
		if err := rcq.loadRecvFile(ctx, query, nodes, nil,
			func(n *RecvChunk, e *RecvFile) { n.Edges.RecvFile = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rcq *RecvChunkQuery) loadRecvFile(ctx context.Context, query *RecvFileQuery, nodes []*RecvChunk, init func(*RecvChunk), assign func(*RecvChunk, *RecvFile)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RecvChunk)
	for i := range nodes {
		fk := nodes[i].RecvfileID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(recvfile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "recvfile_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rcq *RecvChunkQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rcq.querySpec()
	_spec.Node.Columns = rcq.ctx.Fields
	if len(rcq.ctx.Fields) > 0 {
		_spec.Unique = rcq.ctx.Unique != nil && *rcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rcq.driver, _spec)
}

func (rcq *RecvChunkQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(recvchunk.Table, recvchunk.Columns, sqlgraph.NewFieldSpec(recvchunk.FieldID, field.TypeInt))
	_spec.From = rcq.sql
	if unique := rcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rcq.path != nil {
		_spec.Unique = true
	}
	if fields := rcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recvchunk.FieldID)
		for i := range fields {
			if fields[i] != recvchunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if rcq.withRecvFile != nil {
			_spec.Node.AddColumnOnce(recvchunk.FieldRecvfileID)
		}
	}
	if ps := rcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rcq *RecvChunkQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rcq.driver.Dialect())
	t1 := builder.Table(recvchunk.Table)
	columns := rcq.ctx.Fields
	if len(columns) == 0 {
		columns = recvchunk.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rcq.sql != nil {
		selector = rcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rcq.ctx.Unique != nil && *rcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rcq.predicates {
		p(selector)
	}
	for _, p := range rcq.order {
		p(selector)
	}
	if offset := rcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RecvChunkGroupBy is the group-by builder for RecvChunk entities.
type RecvChunkGroupBy struct {
	selector
	build *RecvChunkQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rcgb *RecvChunkGroupBy) Aggregate(fns ...AggregateFunc) *RecvChunkGroupBy {
	rcgb.fns = append(rcgb.fns, fns...)
	return rcgb
}

// Scan applies the selector query and scans the result into the given value.
func (rcgb *RecvChunkGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rcgb.build.ctx, ent.OpQueryGroupBy)
	if err := rcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecvChunkQuery, *RecvChunkGroupBy](ctx, rcgb.build, rcgb, rcgb.build.inters, v)
}

func (rcgb *RecvChunkGroupBy) sqlScan(ctx context.Context, root *RecvChunkQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rcgb.fns))
	for _, fn := range rcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rcgb.flds)+len(rcgb.fns))
		for _, f := range *rcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RecvChunkSelect is the builder for selecting fields of RecvChunk entities.
type RecvChunkSelect struct {
	*RecvChunkQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rcs *RecvChunkSelect) Aggregate(fns ...AggregateFunc) *RecvChunkSelect {
	rcs.fns = append(rcs.fns, fns...)
	return rcs
}

// Scan applies the selector query and scans the result into the given value.
func (rcs *RecvChunkSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rcs.ctx, ent.OpQuerySelect)
	if err := rcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecvChunkQuery, *RecvChunkSelect](ctx, rcs.RecvChunkQuery, rcs, rcs.inters, v)
}

func (rcs *RecvChunkSelect) sqlScan(ctx context.Context, root *RecvChunkQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rcs.fns))
	for _, fn := range rcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
