// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/gogf/gf/v2/os/gctx"
	"github.com/shiqinfeng1/goframe-ddd/internal/filexfer/application"
	"github.com/shiqinfeng1/goframe-ddd/internal/filexfer/domain/filemgr"
	"github.com/shiqinfeng1/goframe-ddd/internal/filexfer/infrastructure/repositories"
	"github.com/shiqinfeng1/goframe-ddd/internal/filexfer/infrastructure/repositories/migration"
	"github.com/shiqinfeng1/goframe-ddd/internal/filexfer/server"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func initServer() (*ghttp.Server, func(), error) {
	context := ProvideContext()
	client := migration.NewEntClient(context)
	repository := repositories.NewFilemgrRepo(client)
	fileTransferMgr := filemgr.NewFileTransferService(context, repository)
	service := application.New(context, fileTransferMgr)
	ghttpServer := server.NewHttpServer(context, service)
	return ghttpServer, func() {
	}, nil
}

// wire.go:

// ProvideContext 提供 context.Context 实例
func ProvideContext() context.Context {
	return gctx.New()
}
