// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shiqinfeng1/goframe-ddd/internal/adapters/ent/predicate"
	"github.com/shiqinfeng1/goframe-ddd/internal/adapters/ent/sendchunk"
	"github.com/shiqinfeng1/goframe-ddd/internal/adapters/ent/sendfile"
)

// SendChunkQuery is the builder for querying SendChunk entities.
type SendChunkQuery struct {
	config
	ctx          *QueryContext
	order        []sendchunk.OrderOption
	inters       []Interceptor
	predicates   []predicate.SendChunk
	withSendFile *SendFileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SendChunkQuery builder.
func (scq *SendChunkQuery) Where(ps ...predicate.SendChunk) *SendChunkQuery {
	scq.predicates = append(scq.predicates, ps...)
	return scq
}

// Limit the number of records to be returned by this query.
func (scq *SendChunkQuery) Limit(limit int) *SendChunkQuery {
	scq.ctx.Limit = &limit
	return scq
}

// Offset to start from.
func (scq *SendChunkQuery) Offset(offset int) *SendChunkQuery {
	scq.ctx.Offset = &offset
	return scq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (scq *SendChunkQuery) Unique(unique bool) *SendChunkQuery {
	scq.ctx.Unique = &unique
	return scq
}

// Order specifies how the records should be ordered.
func (scq *SendChunkQuery) Order(o ...sendchunk.OrderOption) *SendChunkQuery {
	scq.order = append(scq.order, o...)
	return scq
}

// QuerySendFile chains the current query on the "send_file" edge.
func (scq *SendChunkQuery) QuerySendFile() *SendFileQuery {
	query := (&SendFileClient{config: scq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := scq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sendchunk.Table, sendchunk.FieldID, selector),
			sqlgraph.To(sendfile.Table, sendfile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sendchunk.SendFileTable, sendchunk.SendFileColumn),
		)
		fromU = sqlgraph.SetNeighbors(scq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SendChunk entity from the query.
// Returns a *NotFoundError when no SendChunk was found.
func (scq *SendChunkQuery) First(ctx context.Context) (*SendChunk, error) {
	nodes, err := scq.Limit(1).All(setContextOp(ctx, scq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sendchunk.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scq *SendChunkQuery) FirstX(ctx context.Context) *SendChunk {
	node, err := scq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SendChunk ID from the query.
// Returns a *NotFoundError when no SendChunk ID was found.
func (scq *SendChunkQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = scq.Limit(1).IDs(setContextOp(ctx, scq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sendchunk.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scq *SendChunkQuery) FirstIDX(ctx context.Context) int {
	id, err := scq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SendChunk entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SendChunk entity is found.
// Returns a *NotFoundError when no SendChunk entities are found.
func (scq *SendChunkQuery) Only(ctx context.Context) (*SendChunk, error) {
	nodes, err := scq.Limit(2).All(setContextOp(ctx, scq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sendchunk.Label}
	default:
		return nil, &NotSingularError{sendchunk.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scq *SendChunkQuery) OnlyX(ctx context.Context) *SendChunk {
	node, err := scq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SendChunk ID in the query.
// Returns a *NotSingularError when more than one SendChunk ID is found.
// Returns a *NotFoundError when no entities are found.
func (scq *SendChunkQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = scq.Limit(2).IDs(setContextOp(ctx, scq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sendchunk.Label}
	default:
		err = &NotSingularError{sendchunk.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scq *SendChunkQuery) OnlyIDX(ctx context.Context) int {
	id, err := scq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SendChunks.
func (scq *SendChunkQuery) All(ctx context.Context) ([]*SendChunk, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryAll)
	if err := scq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SendChunk, *SendChunkQuery]()
	return withInterceptors[[]*SendChunk](ctx, scq, qr, scq.inters)
}

// AllX is like All, but panics if an error occurs.
func (scq *SendChunkQuery) AllX(ctx context.Context) []*SendChunk {
	nodes, err := scq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SendChunk IDs.
func (scq *SendChunkQuery) IDs(ctx context.Context) (ids []int, err error) {
	if scq.ctx.Unique == nil && scq.path != nil {
		scq.Unique(true)
	}
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryIDs)
	if err = scq.Select(sendchunk.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scq *SendChunkQuery) IDsX(ctx context.Context) []int {
	ids, err := scq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scq *SendChunkQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryCount)
	if err := scq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, scq, querierCount[*SendChunkQuery](), scq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (scq *SendChunkQuery) CountX(ctx context.Context) int {
	count, err := scq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scq *SendChunkQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryExist)
	switch _, err := scq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (scq *SendChunkQuery) ExistX(ctx context.Context) bool {
	exist, err := scq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SendChunkQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scq *SendChunkQuery) Clone() *SendChunkQuery {
	if scq == nil {
		return nil
	}
	return &SendChunkQuery{
		config:       scq.config,
		ctx:          scq.ctx.Clone(),
		order:        append([]sendchunk.OrderOption{}, scq.order...),
		inters:       append([]Interceptor{}, scq.inters...),
		predicates:   append([]predicate.SendChunk{}, scq.predicates...),
		withSendFile: scq.withSendFile.Clone(),
		// clone intermediate query.
		sql:  scq.sql.Clone(),
		path: scq.path,
	}
}

// WithSendFile tells the query-builder to eager-load the nodes that are connected to
// the "send_file" edge. The optional arguments are used to configure the query builder of the edge.
func (scq *SendChunkQuery) WithSendFile(opts ...func(*SendFileQuery)) *SendChunkQuery {
	query := (&SendFileClient{config: scq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	scq.withSendFile = query
	return scq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SendfileID int `json:"sendfile_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SendChunk.Query().
//		GroupBy(sendchunk.FieldSendfileID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (scq *SendChunkQuery) GroupBy(field string, fields ...string) *SendChunkGroupBy {
	scq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SendChunkGroupBy{build: scq}
	grbuild.flds = &scq.ctx.Fields
	grbuild.label = sendchunk.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SendfileID int `json:"sendfile_id,omitempty"`
//	}
//
//	client.SendChunk.Query().
//		Select(sendchunk.FieldSendfileID).
//		Scan(ctx, &v)
func (scq *SendChunkQuery) Select(fields ...string) *SendChunkSelect {
	scq.ctx.Fields = append(scq.ctx.Fields, fields...)
	sbuild := &SendChunkSelect{SendChunkQuery: scq}
	sbuild.label = sendchunk.Label
	sbuild.flds, sbuild.scan = &scq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SendChunkSelect configured with the given aggregations.
func (scq *SendChunkQuery) Aggregate(fns ...AggregateFunc) *SendChunkSelect {
	return scq.Select().Aggregate(fns...)
}

func (scq *SendChunkQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range scq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, scq); err != nil {
				return err
			}
		}
	}
	for _, f := range scq.ctx.Fields {
		if !sendchunk.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if scq.path != nil {
		prev, err := scq.path(ctx)
		if err != nil {
			return err
		}
		scq.sql = prev
	}
	return nil
}

func (scq *SendChunkQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SendChunk, error) {
	var (
		nodes       = []*SendChunk{}
		_spec       = scq.querySpec()
		loadedTypes = [1]bool{
			scq.withSendFile != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SendChunk).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SendChunk{config: scq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, scq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := scq.withSendFile; query != nil {
		if err := scq.loadSendFile(ctx, query, nodes, nil,
			func(n *SendChunk, e *SendFile) { n.Edges.SendFile = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (scq *SendChunkQuery) loadSendFile(ctx context.Context, query *SendFileQuery, nodes []*SendChunk, init func(*SendChunk), assign func(*SendChunk, *SendFile)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SendChunk)
	for i := range nodes {
		fk := nodes[i].SendfileID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sendfile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sendfile_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (scq *SendChunkQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scq.querySpec()
	_spec.Node.Columns = scq.ctx.Fields
	if len(scq.ctx.Fields) > 0 {
		_spec.Unique = scq.ctx.Unique != nil && *scq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, scq.driver, _spec)
}

func (scq *SendChunkQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sendchunk.Table, sendchunk.Columns, sqlgraph.NewFieldSpec(sendchunk.FieldID, field.TypeInt))
	_spec.From = scq.sql
	if unique := scq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if scq.path != nil {
		_spec.Unique = true
	}
	if fields := scq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sendchunk.FieldID)
		for i := range fields {
			if fields[i] != sendchunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if scq.withSendFile != nil {
			_spec.Node.AddColumnOnce(sendchunk.FieldSendfileID)
		}
	}
	if ps := scq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (scq *SendChunkQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(scq.driver.Dialect())
	t1 := builder.Table(sendchunk.Table)
	columns := scq.ctx.Fields
	if len(columns) == 0 {
		columns = sendchunk.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if scq.sql != nil {
		selector = scq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if scq.ctx.Unique != nil && *scq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range scq.predicates {
		p(selector)
	}
	for _, p := range scq.order {
		p(selector)
	}
	if offset := scq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SendChunkGroupBy is the group-by builder for SendChunk entities.
type SendChunkGroupBy struct {
	selector
	build *SendChunkQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scgb *SendChunkGroupBy) Aggregate(fns ...AggregateFunc) *SendChunkGroupBy {
	scgb.fns = append(scgb.fns, fns...)
	return scgb
}

// Scan applies the selector query and scans the result into the given value.
func (scgb *SendChunkGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scgb.build.ctx, ent.OpQueryGroupBy)
	if err := scgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SendChunkQuery, *SendChunkGroupBy](ctx, scgb.build, scgb, scgb.build.inters, v)
}

func (scgb *SendChunkGroupBy) sqlScan(ctx context.Context, root *SendChunkQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(scgb.fns))
	for _, fn := range scgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*scgb.flds)+len(scgb.fns))
		for _, f := range *scgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*scgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SendChunkSelect is the builder for selecting fields of SendChunk entities.
type SendChunkSelect struct {
	*SendChunkQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (scs *SendChunkSelect) Aggregate(fns ...AggregateFunc) *SendChunkSelect {
	scs.fns = append(scs.fns, fns...)
	return scs
}

// Scan applies the selector query and scans the result into the given value.
func (scs *SendChunkSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scs.ctx, ent.OpQuerySelect)
	if err := scs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SendChunkQuery, *SendChunkSelect](ctx, scs.SendChunkQuery, scs, scs.inters, v)
}

func (scs *SendChunkSelect) sqlScan(ctx context.Context, root *SendChunkQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(scs.fns))
	for _, fn := range scs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*scs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
