// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shiqinfeng1/goframe-ddd/internal/adapters/ent/sendchunk"
	"github.com/shiqinfeng1/goframe-ddd/internal/adapters/ent/sendfile"
)

// SendFileCreate is the builder for creating a SendFile entity.
type SendFileCreate struct {
	config
	mutation *SendFileMutation
	hooks    []Hook
}

// SetFilePath sets the "file_path" field.
func (sfc *SendFileCreate) SetFilePath(s string) *SendFileCreate {
	sfc.mutation.SetFilePath(s)
	return sfc
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (sfc *SendFileCreate) SetNillableFilePath(s *string) *SendFileCreate {
	if s != nil {
		sfc.SetFilePath(*s)
	}
	return sfc
}

// SetFileName sets the "file_name" field.
func (sfc *SendFileCreate) SetFileName(s string) *SendFileCreate {
	sfc.mutation.SetFileName(s)
	return sfc
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (sfc *SendFileCreate) SetNillableFileName(s *string) *SendFileCreate {
	if s != nil {
		sfc.SetFileName(*s)
	}
	return sfc
}

// SetFid sets the "fid" field.
func (sfc *SendFileCreate) SetFid(s string) *SendFileCreate {
	sfc.mutation.SetFid(s)
	return sfc
}

// SetFileSize sets the "file_size" field.
func (sfc *SendFileCreate) SetFileSize(i int64) *SendFileCreate {
	sfc.mutation.SetFileSize(i)
	return sfc
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (sfc *SendFileCreate) SetNillableFileSize(i *int64) *SendFileCreate {
	if i != nil {
		sfc.SetFileSize(*i)
	}
	return sfc
}

// SetChunkNumTotal sets the "chunk_num_total" field.
func (sfc *SendFileCreate) SetChunkNumTotal(i int) *SendFileCreate {
	sfc.mutation.SetChunkNumTotal(i)
	return sfc
}

// SetNillableChunkNumTotal sets the "chunk_num_total" field if the given value is not nil.
func (sfc *SendFileCreate) SetNillableChunkNumTotal(i *int) *SendFileCreate {
	if i != nil {
		sfc.SetChunkNumTotal(*i)
	}
	return sfc
}

// SetChunkNumSended sets the "chunk_num_sended" field.
func (sfc *SendFileCreate) SetChunkNumSended(i int) *SendFileCreate {
	sfc.mutation.SetChunkNumSended(i)
	return sfc
}

// SetNillableChunkNumSended sets the "chunk_num_sended" field if the given value is not nil.
func (sfc *SendFileCreate) SetNillableChunkNumSended(i *int) *SendFileCreate {
	if i != nil {
		sfc.SetChunkNumSended(*i)
	}
	return sfc
}

// SetStatus sets the "status" field.
func (sfc *SendFileCreate) SetStatus(i int) *SendFileCreate {
	sfc.mutation.SetStatus(i)
	return sfc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sfc *SendFileCreate) SetNillableStatus(i *int) *SendFileCreate {
	if i != nil {
		sfc.SetStatus(*i)
	}
	return sfc
}

// SetElapsed sets the "elapsed" field.
func (sfc *SendFileCreate) SetElapsed(s string) *SendFileCreate {
	sfc.mutation.SetElapsed(s)
	return sfc
}

// SetNillableElapsed sets the "elapsed" field if the given value is not nil.
func (sfc *SendFileCreate) SetNillableElapsed(s *string) *SendFileCreate {
	if s != nil {
		sfc.SetElapsed(*s)
	}
	return sfc
}

// SetSpeed sets the "speed" field.
func (sfc *SendFileCreate) SetSpeed(s string) *SendFileCreate {
	sfc.mutation.SetSpeed(s)
	return sfc
}

// SetNillableSpeed sets the "speed" field if the given value is not nil.
func (sfc *SendFileCreate) SetNillableSpeed(s *string) *SendFileCreate {
	if s != nil {
		sfc.SetSpeed(*s)
	}
	return sfc
}

// SetUpdatedAt sets the "updated_at" field.
func (sfc *SendFileCreate) SetUpdatedAt(t time.Time) *SendFileCreate {
	sfc.mutation.SetUpdatedAt(t)
	return sfc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sfc *SendFileCreate) SetNillableUpdatedAt(t *time.Time) *SendFileCreate {
	if t != nil {
		sfc.SetUpdatedAt(*t)
	}
	return sfc
}

// SetCreatedAt sets the "created_at" field.
func (sfc *SendFileCreate) SetCreatedAt(t time.Time) *SendFileCreate {
	sfc.mutation.SetCreatedAt(t)
	return sfc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sfc *SendFileCreate) SetNillableCreatedAt(t *time.Time) *SendFileCreate {
	if t != nil {
		sfc.SetCreatedAt(*t)
	}
	return sfc
}

// AddSendChunkIDs adds the "send_chunks" edge to the SendChunk entity by IDs.
func (sfc *SendFileCreate) AddSendChunkIDs(ids ...int) *SendFileCreate {
	sfc.mutation.AddSendChunkIDs(ids...)
	return sfc
}

// AddSendChunks adds the "send_chunks" edges to the SendChunk entity.
func (sfc *SendFileCreate) AddSendChunks(s ...*SendChunk) *SendFileCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sfc.AddSendChunkIDs(ids...)
}

// Mutation returns the SendFileMutation object of the builder.
func (sfc *SendFileCreate) Mutation() *SendFileMutation {
	return sfc.mutation
}

// Save creates the SendFile in the database.
func (sfc *SendFileCreate) Save(ctx context.Context) (*SendFile, error) {
	sfc.defaults()
	return withHooks(ctx, sfc.sqlSave, sfc.mutation, sfc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sfc *SendFileCreate) SaveX(ctx context.Context) *SendFile {
	v, err := sfc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sfc *SendFileCreate) Exec(ctx context.Context) error {
	_, err := sfc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfc *SendFileCreate) ExecX(ctx context.Context) {
	if err := sfc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sfc *SendFileCreate) defaults() {
	if _, ok := sfc.mutation.FileSize(); !ok {
		v := sendfile.DefaultFileSize
		sfc.mutation.SetFileSize(v)
	}
	if _, ok := sfc.mutation.ChunkNumTotal(); !ok {
		v := sendfile.DefaultChunkNumTotal
		sfc.mutation.SetChunkNumTotal(v)
	}
	if _, ok := sfc.mutation.ChunkNumSended(); !ok {
		v := sendfile.DefaultChunkNumSended
		sfc.mutation.SetChunkNumSended(v)
	}
	if _, ok := sfc.mutation.Status(); !ok {
		v := sendfile.DefaultStatus
		sfc.mutation.SetStatus(v)
	}
	if _, ok := sfc.mutation.Elapsed(); !ok {
		v := sendfile.DefaultElapsed
		sfc.mutation.SetElapsed(v)
	}
	if _, ok := sfc.mutation.Speed(); !ok {
		v := sendfile.DefaultSpeed
		sfc.mutation.SetSpeed(v)
	}
	if _, ok := sfc.mutation.UpdatedAt(); !ok {
		v := sendfile.DefaultUpdatedAt()
		sfc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sfc.mutation.CreatedAt(); !ok {
		v := sendfile.DefaultCreatedAt()
		sfc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sfc *SendFileCreate) check() error {
	if _, ok := sfc.mutation.Fid(); !ok {
		return &ValidationError{Name: "fid", err: errors.New(`ent: missing required field "SendFile.fid"`)}
	}
	if _, ok := sfc.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "SendFile.file_size"`)}
	}
	if _, ok := sfc.mutation.ChunkNumTotal(); !ok {
		return &ValidationError{Name: "chunk_num_total", err: errors.New(`ent: missing required field "SendFile.chunk_num_total"`)}
	}
	if _, ok := sfc.mutation.ChunkNumSended(); !ok {
		return &ValidationError{Name: "chunk_num_sended", err: errors.New(`ent: missing required field "SendFile.chunk_num_sended"`)}
	}
	if _, ok := sfc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SendFile.status"`)}
	}
	if _, ok := sfc.mutation.Elapsed(); !ok {
		return &ValidationError{Name: "elapsed", err: errors.New(`ent: missing required field "SendFile.elapsed"`)}
	}
	if v, ok := sfc.mutation.Elapsed(); ok {
		if err := sendfile.ElapsedValidator(v); err != nil {
			return &ValidationError{Name: "elapsed", err: fmt.Errorf(`ent: validator failed for field "SendFile.elapsed": %w`, err)}
		}
	}
	if _, ok := sfc.mutation.Speed(); !ok {
		return &ValidationError{Name: "speed", err: errors.New(`ent: missing required field "SendFile.speed"`)}
	}
	if v, ok := sfc.mutation.Speed(); ok {
		if err := sendfile.SpeedValidator(v); err != nil {
			return &ValidationError{Name: "speed", err: fmt.Errorf(`ent: validator failed for field "SendFile.speed": %w`, err)}
		}
	}
	if _, ok := sfc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SendFile.updated_at"`)}
	}
	if _, ok := sfc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SendFile.created_at"`)}
	}
	return nil
}

func (sfc *SendFileCreate) sqlSave(ctx context.Context) (*SendFile, error) {
	if err := sfc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sfc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sfc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sfc.mutation.id = &_node.ID
	sfc.mutation.done = true
	return _node, nil
}

func (sfc *SendFileCreate) createSpec() (*SendFile, *sqlgraph.CreateSpec) {
	var (
		_node = &SendFile{config: sfc.config}
		_spec = sqlgraph.NewCreateSpec(sendfile.Table, sqlgraph.NewFieldSpec(sendfile.FieldID, field.TypeInt))
	)
	if value, ok := sfc.mutation.FilePath(); ok {
		_spec.SetField(sendfile.FieldFilePath, field.TypeString, value)
		_node.FilePath = &value
	}
	if value, ok := sfc.mutation.FileName(); ok {
		_spec.SetField(sendfile.FieldFileName, field.TypeString, value)
		_node.FileName = &value
	}
	if value, ok := sfc.mutation.Fid(); ok {
		_spec.SetField(sendfile.FieldFid, field.TypeString, value)
		_node.Fid = value
	}
	if value, ok := sfc.mutation.FileSize(); ok {
		_spec.SetField(sendfile.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := sfc.mutation.ChunkNumTotal(); ok {
		_spec.SetField(sendfile.FieldChunkNumTotal, field.TypeInt, value)
		_node.ChunkNumTotal = value
	}
	if value, ok := sfc.mutation.ChunkNumSended(); ok {
		_spec.SetField(sendfile.FieldChunkNumSended, field.TypeInt, value)
		_node.ChunkNumSended = value
	}
	if value, ok := sfc.mutation.Status(); ok {
		_spec.SetField(sendfile.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := sfc.mutation.Elapsed(); ok {
		_spec.SetField(sendfile.FieldElapsed, field.TypeString, value)
		_node.Elapsed = value
	}
	if value, ok := sfc.mutation.Speed(); ok {
		_spec.SetField(sendfile.FieldSpeed, field.TypeString, value)
		_node.Speed = value
	}
	if value, ok := sfc.mutation.UpdatedAt(); ok {
		_spec.SetField(sendfile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sfc.mutation.CreatedAt(); ok {
		_spec.SetField(sendfile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := sfc.mutation.SendChunksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sendfile.SendChunksTable,
			Columns: []string{sendfile.SendChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sendchunk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SendFileCreateBulk is the builder for creating many SendFile entities in bulk.
type SendFileCreateBulk struct {
	config
	err      error
	builders []*SendFileCreate
}

// Save creates the SendFile entities in the database.
func (sfcb *SendFileCreateBulk) Save(ctx context.Context) ([]*SendFile, error) {
	if sfcb.err != nil {
		return nil, sfcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sfcb.builders))
	nodes := make([]*SendFile, len(sfcb.builders))
	mutators := make([]Mutator, len(sfcb.builders))
	for i := range sfcb.builders {
		func(i int, root context.Context) {
			builder := sfcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SendFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sfcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sfcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sfcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sfcb *SendFileCreateBulk) SaveX(ctx context.Context) []*SendFile {
	v, err := sfcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sfcb *SendFileCreateBulk) Exec(ctx context.Context) error {
	_, err := sfcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfcb *SendFileCreateBulk) ExecX(ctx context.Context) {
	if err := sfcb.Exec(ctx); err != nil {
		panic(err)
	}
}
