// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package filemgr

import (
	"github.com/shiqinfeng1/goframe-ddd/api/filexfer/http/filemgr"
	"github.com/shiqinfeng1/goframe-ddd/internal/filexfer/application"
)

type ControllerV1 struct {
	app *application.Service
}

func NewV1(app *application.Service) filemgr.IFilemgrV1 {
	return &ControllerV1{
		app: app,
	}
}
