// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package session

import (
	"github.com/shiqinfeng1/goframe-ddd/api/demo/http/session"
	"github.com/shiqinfeng1/goframe-ddd/internal/demo/application"
)

type ControllerV1 struct {
	app *application.Service
}

func NewV1(app *application.Service) session.ISessionV1 {
	return &ControllerV1{
		app: app,
	}
}
