// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	"github.com/shiqinfeng1/goframe-ddd/api/mgrid/http/auth"
	"github.com/shiqinfeng1/goframe-ddd/internal/mgrid/server"
)

type ControllerV1 struct {
	logger server.Logger
}

func NewV1(logger server.Logger) auth.IAuthV1 {
	return &ControllerV1{
		logger: logger,
	}
}
