// Code generated by ent, DO NOT EDIT.

package sendfile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shiqinfeng1/goframe-ddd/internal/infrastructure/repositories/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SendFile {
	return predicate.SendFile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SendFile {
	return predicate.SendFile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SendFile {
	return predicate.SendFile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SendFile {
	return predicate.SendFile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SendFile {
	return predicate.SendFile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SendFile {
	return predicate.SendFile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SendFile {
	return predicate.SendFile(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldTaskID, v))
}

// FilePath applies equality check predicate on the "file_path" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldFilePath, v))
}

// FileID applies equality check predicate on the "file_id" field. It's identical to FileIDEQ.
func FileID(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldFileID, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int64) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldFileSize, v))
}

// ChunkNumTotal applies equality check predicate on the "chunk_num_total" field. It's identical to ChunkNumTotalEQ.
func ChunkNumTotal(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldChunkNumTotal, v))
}

// ChunkNumSended applies equality check predicate on the "chunk_num_sended" field. It's identical to ChunkNumSendedEQ.
func ChunkNumSended(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldChunkNumSended, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldStatus, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldCreatedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.SendFile {
	return predicate.SendFile(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.SendFile {
	return predicate.SendFile(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldContainsFold(FieldTaskID, v))
}

// FilePathEQ applies the EQ predicate on the "file_path" field.
func FilePathEQ(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldFilePath, v))
}

// FilePathNEQ applies the NEQ predicate on the "file_path" field.
func FilePathNEQ(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldNEQ(FieldFilePath, v))
}

// FilePathIn applies the In predicate on the "file_path" field.
func FilePathIn(vs ...string) predicate.SendFile {
	return predicate.SendFile(sql.FieldIn(FieldFilePath, vs...))
}

// FilePathNotIn applies the NotIn predicate on the "file_path" field.
func FilePathNotIn(vs ...string) predicate.SendFile {
	return predicate.SendFile(sql.FieldNotIn(FieldFilePath, vs...))
}

// FilePathGT applies the GT predicate on the "file_path" field.
func FilePathGT(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldGT(FieldFilePath, v))
}

// FilePathGTE applies the GTE predicate on the "file_path" field.
func FilePathGTE(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldGTE(FieldFilePath, v))
}

// FilePathLT applies the LT predicate on the "file_path" field.
func FilePathLT(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldLT(FieldFilePath, v))
}

// FilePathLTE applies the LTE predicate on the "file_path" field.
func FilePathLTE(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldLTE(FieldFilePath, v))
}

// FilePathContains applies the Contains predicate on the "file_path" field.
func FilePathContains(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldContains(FieldFilePath, v))
}

// FilePathHasPrefix applies the HasPrefix predicate on the "file_path" field.
func FilePathHasPrefix(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldHasPrefix(FieldFilePath, v))
}

// FilePathHasSuffix applies the HasSuffix predicate on the "file_path" field.
func FilePathHasSuffix(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldHasSuffix(FieldFilePath, v))
}

// FilePathEqualFold applies the EqualFold predicate on the "file_path" field.
func FilePathEqualFold(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldEqualFold(FieldFilePath, v))
}

// FilePathContainsFold applies the ContainsFold predicate on the "file_path" field.
func FilePathContainsFold(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldContainsFold(FieldFilePath, v))
}

// FileIDEQ applies the EQ predicate on the "file_id" field.
func FileIDEQ(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldFileID, v))
}

// FileIDNEQ applies the NEQ predicate on the "file_id" field.
func FileIDNEQ(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldNEQ(FieldFileID, v))
}

// FileIDIn applies the In predicate on the "file_id" field.
func FileIDIn(vs ...string) predicate.SendFile {
	return predicate.SendFile(sql.FieldIn(FieldFileID, vs...))
}

// FileIDNotIn applies the NotIn predicate on the "file_id" field.
func FileIDNotIn(vs ...string) predicate.SendFile {
	return predicate.SendFile(sql.FieldNotIn(FieldFileID, vs...))
}

// FileIDGT applies the GT predicate on the "file_id" field.
func FileIDGT(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldGT(FieldFileID, v))
}

// FileIDGTE applies the GTE predicate on the "file_id" field.
func FileIDGTE(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldGTE(FieldFileID, v))
}

// FileIDLT applies the LT predicate on the "file_id" field.
func FileIDLT(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldLT(FieldFileID, v))
}

// FileIDLTE applies the LTE predicate on the "file_id" field.
func FileIDLTE(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldLTE(FieldFileID, v))
}

// FileIDContains applies the Contains predicate on the "file_id" field.
func FileIDContains(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldContains(FieldFileID, v))
}

// FileIDHasPrefix applies the HasPrefix predicate on the "file_id" field.
func FileIDHasPrefix(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldHasPrefix(FieldFileID, v))
}

// FileIDHasSuffix applies the HasSuffix predicate on the "file_id" field.
func FileIDHasSuffix(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldHasSuffix(FieldFileID, v))
}

// FileIDEqualFold applies the EqualFold predicate on the "file_id" field.
func FileIDEqualFold(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldEqualFold(FieldFileID, v))
}

// FileIDContainsFold applies the ContainsFold predicate on the "file_id" field.
func FileIDContainsFold(v string) predicate.SendFile {
	return predicate.SendFile(sql.FieldContainsFold(FieldFileID, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int64) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int64) predicate.SendFile {
	return predicate.SendFile(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int64) predicate.SendFile {
	return predicate.SendFile(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int64) predicate.SendFile {
	return predicate.SendFile(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int64) predicate.SendFile {
	return predicate.SendFile(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int64) predicate.SendFile {
	return predicate.SendFile(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int64) predicate.SendFile {
	return predicate.SendFile(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int64) predicate.SendFile {
	return predicate.SendFile(sql.FieldLTE(FieldFileSize, v))
}

// ChunkNumTotalEQ applies the EQ predicate on the "chunk_num_total" field.
func ChunkNumTotalEQ(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldChunkNumTotal, v))
}

// ChunkNumTotalNEQ applies the NEQ predicate on the "chunk_num_total" field.
func ChunkNumTotalNEQ(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldNEQ(FieldChunkNumTotal, v))
}

// ChunkNumTotalIn applies the In predicate on the "chunk_num_total" field.
func ChunkNumTotalIn(vs ...int) predicate.SendFile {
	return predicate.SendFile(sql.FieldIn(FieldChunkNumTotal, vs...))
}

// ChunkNumTotalNotIn applies the NotIn predicate on the "chunk_num_total" field.
func ChunkNumTotalNotIn(vs ...int) predicate.SendFile {
	return predicate.SendFile(sql.FieldNotIn(FieldChunkNumTotal, vs...))
}

// ChunkNumTotalGT applies the GT predicate on the "chunk_num_total" field.
func ChunkNumTotalGT(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldGT(FieldChunkNumTotal, v))
}

// ChunkNumTotalGTE applies the GTE predicate on the "chunk_num_total" field.
func ChunkNumTotalGTE(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldGTE(FieldChunkNumTotal, v))
}

// ChunkNumTotalLT applies the LT predicate on the "chunk_num_total" field.
func ChunkNumTotalLT(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldLT(FieldChunkNumTotal, v))
}

// ChunkNumTotalLTE applies the LTE predicate on the "chunk_num_total" field.
func ChunkNumTotalLTE(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldLTE(FieldChunkNumTotal, v))
}

// ChunkNumSendedEQ applies the EQ predicate on the "chunk_num_sended" field.
func ChunkNumSendedEQ(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldChunkNumSended, v))
}

// ChunkNumSendedNEQ applies the NEQ predicate on the "chunk_num_sended" field.
func ChunkNumSendedNEQ(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldNEQ(FieldChunkNumSended, v))
}

// ChunkNumSendedIn applies the In predicate on the "chunk_num_sended" field.
func ChunkNumSendedIn(vs ...int) predicate.SendFile {
	return predicate.SendFile(sql.FieldIn(FieldChunkNumSended, vs...))
}

// ChunkNumSendedNotIn applies the NotIn predicate on the "chunk_num_sended" field.
func ChunkNumSendedNotIn(vs ...int) predicate.SendFile {
	return predicate.SendFile(sql.FieldNotIn(FieldChunkNumSended, vs...))
}

// ChunkNumSendedGT applies the GT predicate on the "chunk_num_sended" field.
func ChunkNumSendedGT(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldGT(FieldChunkNumSended, v))
}

// ChunkNumSendedGTE applies the GTE predicate on the "chunk_num_sended" field.
func ChunkNumSendedGTE(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldGTE(FieldChunkNumSended, v))
}

// ChunkNumSendedLT applies the LT predicate on the "chunk_num_sended" field.
func ChunkNumSendedLT(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldLT(FieldChunkNumSended, v))
}

// ChunkNumSendedLTE applies the LTE predicate on the "chunk_num_sended" field.
func ChunkNumSendedLTE(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldLTE(FieldChunkNumSended, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int) predicate.SendFile {
	return predicate.SendFile(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int) predicate.SendFile {
	return predicate.SendFile(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int) predicate.SendFile {
	return predicate.SendFile(sql.FieldLTE(FieldStatus, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SendFile {
	return predicate.SendFile(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSendChunks applies the HasEdge predicate on the "send_chunks" edge.
func HasSendChunks() predicate.SendFile {
	return predicate.SendFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SendChunksTable, SendChunksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSendChunksWith applies the HasEdge predicate on the "send_chunks" edge with a given conditions (other predicates).
func HasSendChunksWith(preds ...predicate.SendChunk) predicate.SendFile {
	return predicate.SendFile(func(s *sql.Selector) {
		step := newSendChunksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SendFile) predicate.SendFile {
	return predicate.SendFile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SendFile) predicate.SendFile {
	return predicate.SendFile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SendFile) predicate.SendFile {
	return predicate.SendFile(sql.NotPredicates(p))
}
