// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ops

import (
	"context"
	"log"

	"github.com/shiqinfeng1/goframe-ddd/api/mgrid/http/ops"
	"github.com/shiqinfeng1/goframe-ddd/internal/mgrid/application"
	"github.com/shiqinfeng1/goframe-ddd/pkg/dockerctl"
	"github.com/shiqinfeng1/goframe-ddd/pkg/dockerctl/dockercmd"
)

type ControllerV1 struct {
	app       *application.Application
	dockerOps dockerctl.DockerOps
}

func NewV1() ops.IOpsV1 {
	ctx := context.Background()

	// 实例化一个dockeecompose 控制器
	dockerOps, err := dockercmd.New(ctx)
	if err != nil {
		log.Fatal(ctx, err)
	}
	return &ControllerV1{
		app:       application.App(ctx),
		dockerOps: dockerOps,
	}
}
