// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/shiqinfeng1/goframe-ddd/internal/filexfer/infrastructure/repositories/ent/runtime.go

const (
	Version = "v0.14.3"                                         // Version of ent codegen.
	Sum     = "h1:wokAV/kIlH9TeklJWGGS7AYJdVckr0DloWjIcO9iIIQ=" // Sum of ent codegen.
)
