// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package pointdata

import (
	"github.com/shiqinfeng1/goframe-ddd/api/mgrid/http/pointdata"
	"github.com/shiqinfeng1/goframe-ddd/internal/mgrid/application"
	"github.com/shiqinfeng1/goframe-ddd/internal/mgrid/server"
)

type ControllerV1 struct {
	logger server.Logger
	app    application.Service
}

func NewV1(logger server.Logger, app application.Service) pointdata.IPointdataV1 {
	return &ControllerV1{
		logger: logger,
		app:    app,
	}
}
