// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package pointdata

import (
	"github.com/shiqinfeng1/goframe-ddd/api/mgrid/http/pointdata"
	"github.com/shiqinfeng1/goframe-ddd/internal/mgrid/application"
)

type ControllerV1 struct {
	app application.Service
}

func NewV1(app application.Service) pointdata.IPointdataV1 {
	return &ControllerV1{
		app: app,
	}
}
