// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ops

import (
	"github.com/shiqinfeng1/goframe-ddd/api/mgrid/http/ops"
)

type ControllerV1 struct{}

func NewV1() ops.IOpsV1 {
	return &ControllerV1{}
}
