// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package filemgr

import (
	"github.com/shiqinfeng1/goframe-ddd/api/filexfer/http/filemgr"
)

type ControllerV1 struct{}

func NewV1() filemgr.IFilemgrV1 {
	return &ControllerV1{}
}
