// Indicates the protocol buffer version that is being used

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: filemgr/v1/send.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"other fields that can be passed"` // other fields that can be passed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_filemgr_v1_send_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filemgr_v1_send_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_filemgr_v1_send_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty" dc:"other customer related fields"` // other customer related fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_filemgr_v1_send_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filemgr_v1_send_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_filemgr_v1_send_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SayHelloResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SayHelloResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_filemgr_v1_send_proto protoreflect.FileDescriptor

const file_filemgr_v1_send_proto_rawDesc = "" +
	"\n" +
	"\x15filemgr/v1/send.proto\"5\n" +
	"\x0fSayHelloRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"P\n" +
	"\x10SayHelloResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress2A\n" +
	"\fHelloService\x121\n" +
	"\bSayHello\x12\x10.SayHelloRequest\x1a\x11.SayHelloResponse\"\x00B8Z6github.com/shiqinfeng1/goframe-ddd/api/grpc/filemgr/v1b\x06proto3"

var (
	file_filemgr_v1_send_proto_rawDescOnce sync.Once
	file_filemgr_v1_send_proto_rawDescData []byte
)

func file_filemgr_v1_send_proto_rawDescGZIP() []byte {
	file_filemgr_v1_send_proto_rawDescOnce.Do(func() {
		file_filemgr_v1_send_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filemgr_v1_send_proto_rawDesc), len(file_filemgr_v1_send_proto_rawDesc)))
	})
	return file_filemgr_v1_send_proto_rawDescData
}

var file_filemgr_v1_send_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_filemgr_v1_send_proto_goTypes = []any{
	(*SayHelloRequest)(nil),  // 0: SayHelloRequest
	(*SayHelloResponse)(nil), // 1: SayHelloResponse
}
var file_filemgr_v1_send_proto_depIdxs = []int32{
	0, // 0: HelloService.SayHello:input_type -> SayHelloRequest
	1, // 1: HelloService.SayHello:output_type -> SayHelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filemgr_v1_send_proto_init() }
func file_filemgr_v1_send_proto_init() {
	if File_filemgr_v1_send_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filemgr_v1_send_proto_rawDesc), len(file_filemgr_v1_send_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filemgr_v1_send_proto_goTypes,
		DependencyIndexes: file_filemgr_v1_send_proto_depIdxs,
		MessageInfos:      file_filemgr_v1_send_proto_msgTypes,
	}.Build()
	File_filemgr_v1_send_proto = out.File
	file_filemgr_v1_send_proto_goTypes = nil
	file_filemgr_v1_send_proto_depIdxs = nil
}
